name: deploy website
on:
  # 手動で GitHub Actions を実行可能にする設定
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'main'
        required: true
  # 奇数時間ごとに GitHub Actions を実行する設定 (cron の時刻は UTC)
  schedule:
    - cron:  '0 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      # 投稿内容を更新するために npm run build:posts を実行
      - name: Recreate all posts
        shell: bash
        run: |
          npm install
          npm run build:posts
      - uses: amondnet/vercel-action@v20
        with:
          # GitHub Actions の Secrets で作成した値を参照する形で
          # Vercel デプロイ時に必要となる各種パラメタを設定
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID }}  # Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} # Required
          working-directory: ./
